name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push the image
        run: docker build . --file Dockerfile --tag ghcr.io/outclimb/registration:latest --tag oghcr.io/utclimb/registration:${{ github.sha }} --push
